info:
  contact: {}
paths:
  /user/:
    post:
      description: Returns a test message
      responses:
        "200":
          description: hello world
          schema:
            type: string
      summary: Get CREATE USER
  /user/{id}:
    delete:
      description: Returns a test message
      responses:
        "200":
          description: hello world
          schema:
            type: string
      summary: Get DELETE USER
swagger: "2.0"
